.github/workflows/d4l-ci-kmp.yml

Remove upload to codecov

---

README.adoc
README.md

- Add jitpack maven to readme repolist, otherwise the AppAuth-Lib will not be found

Add jitpack maven repository to readme repo list

---

README.adoc

Add paragraph about client configuration to the readme to cover all setups necessary to setup the SDK

Add client configuration to readme

---

CHANGELOG.md
buildSrc/src/main/kotlin/LibraryConfig.kt

Bump version and update Changelog

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Versions.kt

Need to update D4L FHIR libraries because of a bug with FHIR 4
* D4L FHIR SDK 1.0.0 -> 1.1.0
* D4L FHIR Helper SDK 1.4.0 -> 1.4.1

Bump FHIR libraries

---

.github/workflows/d4l-ci-latest-version.yml

Remove git branch and checkout as we are already on main
Fix broken CI job

Fix latest version ci job

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/LibraryConfig.kt

Updated LibraryConfig and added new Changelog section

Pepare release of 1.9.0 Release Candidate 1

---

.github/workflows/d4l-ci-publish-release.yml

Fix release CI job failing on `git checkout -D`

Fix release ci job

---

CHANGELOG.adoc

Prepare release 1.9.0

---

.github/workflows/d4l-ci-publish-release.yml

Remove `git branch` and `git checkout`

Fix CI release job

---

CHANGELOG.adoc
sdk-core/src/main/java/care/data4life/sdk/SdkContract.kt
sdk-core/src/main/java/care/data4life/sdk/auth/AuthClient.kt
sdk-core/src/main/java/care/data4life/sdk/data/DataRecordClient.kt
sdk-core/src/main/java/care/data4life/sdk/fhir/Fhir4RecordClient.kt

The SDKContract is changed to ensure cancelable operations for all api calls. This is now available via Tasks and added where it was missing.
All operations should be cancelable

Fix api task exposure

---

CHANGELOG.adoc
sdk-core/src/main/java/care/data4life/sdk/call/CallHandler.kt
sdk-core/src/test/java/care/data4life/sdk/call/CallHandlerTest.kt
sdk-core/src/test/java/care/data4life/sdk/test/util/TestRxSchedulerRule.kt

Callback and Listener `onError()` cases are now also logged as `Log.error()` of our D4L Logger.
At the moment the experience using the logger is not consistent as not all errors are logged. Errors communicated using our callbacks and listeners are not covered yet.
Force exceptions and validate Logger output.

Fix Logger

---

.github/CODEOWNERS

Add CODEOWNER file and assign the PHDC Core KMP Team to it

Add codeowner file and set it to PHDC Core KMP team

---

sdk-core/src/main/java/care/data4life/sdk/ImageResizer.kt

Currently the ImageResizer is marked as  `internal`, but is used outside of the module.
The `internal` keyword had been removed for the ImageResizer.
No additional tests had been added.

Fix visibility of ImageResizer

---

.github/workflows/d4l-ci-pull-request-validation.yml
buildSrc/src/main/kotlin/scripts/versioning.gradle.kts
gradle.properties

Change the CI Jobs to properly generate versions based on the job executed
- Fix publish job by patching the versioning script to allow the branch name to be null, as we only need the tag
-  Change pull-request validation job to use the branch reference and remove custom checkout

Fix versioning for releases and improve pull-request job

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
sample-android/build.gradle.kts
sample-jvm/build.gradle.kts
sdk-android-test/build.gradle.kts
sdk-android/build.gradle.kts
sdk-core/build.gradle.kts
sdk-ingestion/build.gradle.kts
sdk-jvm/build.gradle.kts

Bump HC-FHIR-SDK from 1.1.0 to 1.2.1

Bump HC-FHIR-SDK 1.1.0 -> 1.2.1

---

CHANGELOG.adoc
README.adoc

Prepare release of v1.9.1 by updating Readme and Changelog
Also fixed wrong links in Readme file

Prepare release v1.9.1

---

buildSrc/src/main/kotlin/scripts/versioning.gradle.kts

Fix regex pattern to find branch names with ticket numbers

Fix versioning for ticket branches

---

CHANGELOG.adoc
README.adoc

Prepare release of version 1.9.2

Prepare release 1.9.2

---

CHANGELOG.adoc
sdk-core/src/main/java/care/data4life/sdk/ApiService.java
sdk-core/src/main/java/care/data4life/sdk/migration/RecordCompatibilityService.kt
sdk-core/src/main/java/care/data4life/sdk/network/IHCService.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceCountRecordsIntegration.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceFetchIntegration.kt
sdk-core/src/test/java/care/data4life/sdk/migration/RecordCompatibilityServiceTest.kt

This fixes the currently broken api calls for search/fetchRecords and countRecords.
Currently the calls fetching all records of a user, since the it does not respect the query schema.
The query schema had been adjusted alongside with necessary changes and the calling classes (CompatibilityService) .
The tests of CompatibilityService and the module tests of fetchRecords as well as countRecords had to be changed.

[NAT-626]Fix api search and count api calls

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Versions.kt
sdk-core/src/main/java/care/data4life/sdk/wrapper/SdkFhirElementFactory.kt

This updates the HC FHIR library and removes the outdated normilzer in the ElementFactorWrapper.

Update  HC FHIR library

---

CHANGELOG.adoc
README.adoc
buildSrc/src/main/kotlin/LibraryConfig.kt

Prepare release 1.10.0

---

.github/workflows/d4l-ci-pull-request-precheck.yml
Dangerfile.df.kts
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/GradlePlugins.kt
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/scripts/dependency-updates.gradle.kts
buildSrc/src/main/kotlin/scripts/download-scripts.gradle.kts
buildSrc/src/main/kotlin/scripts/publishing.gradle.kts
buildSrc/src/main/kotlin/scripts/versioning.gradle.kts

Add [Danger Kotlin](https://github.com/danger/kotlin) as pull-request validation CI workflow
Also added a Gradle script to download latest version of scripts and configuration from our central repository.
Updated existing scripts
Improve consistency and automatically check that pull-requests follow our contribution guides

Add danger

---

.github/workflows/d4l-ci-pull-request-precheck.yml
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/scripts/quality-spotless.gradle.kts

Danger workflow was broken because of a missing dependency. Switched to the new docker container images available, which also speeds up validation as the danger-kotlin versions doesn't need to be compiled anymore.
Changed Spotless script to latest version

Fix Danger workflow

---

CHANGELOG.adoc
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/AndroidConfig.kt
buildSrc/src/main/kotlin/LibraryConfig.kt
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/scripts/quality-spotless.gradle.kts
gradle/wrapper/gradle-wrapper.properties
sdk-android/src/test/java/care/data4life/sdk/crypto/ExchangeKeyFactoryTest.java
sdk-core/src/main/java/care/data4life/sdk/fhir/Fhir4RecordClient.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceTest.kt

Bump updates:
Kotlin 1.3.75 -> 1.4.32
Gradle 6.7.1 -> 6.8.3
Android 4.1.1 -> 4.1.3
ktlint: 0.41 -> 0.41
targetSdkVersion & compileSdkVersion 29 -> 30
minSdkVersion 21 -> 23
We have to update to resolve the moshi issue.

Bump updates

---

CHANGELOG.adoc
sdk-core/src/main/java/care/data4life/sdk/network/model/CommonKeyResponse.kt
sdk-core/src/main/java/care/data4life/sdk/network/model/DocumentUploadResponse.kt
sdk-core/src/test/java/care/data4life/sdk/network/CommonKeyResponseTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/DocumentUploadResponseTest.kt

This simply fixes DocumentUploadResponse and CommonKeyResponse.
DocumentUploadResponse and CommonKeyResponse are not correctly serialized at the moment.
It simply uses not `@field:Json` instead of `@Json on fields.
The already existing tests had been changed accordingly.

Fix DocumentUploadResponse and CommonKeyResponse

---

sdk-core/src/test/java/care/data4life/sdk/RecordServiceCountRecordsModuleTest.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceCreationRecordModuleTest.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceFetchRecordsModuleTest.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceModuleTestFlowHelper.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceUpdateRecordModuleTest.kt

This makes the order of tags in module tests arbitrarily.
Currently the order of tags can cause problems during the module tests.
This is part of [SDK-566](https://gesundheitscloud.atlassian.net/browse/SDK-566).
It now captures the Tags in the api mocks and make the comparisons via new helper methods of the FlowHelper.

[SDK-566] Change Module tests tag order

---

sdk-core/src/test/java/care/data4life/sdk/tag/TagEncryptionHelperTest.kt
sdk-core/src/test/java/care/data4life/sdk/tag/TagEncryptionServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/tag/TaggingServiceTest.kt

This aligns the already existing tests for TaggingService, TagEncryptionHelper and TagEncryptionService.
This is part of [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563) and depends on #111.
It aligns the already existing tests to the established patterns and closes minor blindspots.

[SDK-563] Change Tagging tests

---

sdk-android/src/main/java/care/data4life/sdk/Data4LifeClient.java
sdk-core/src/main/java/care/data4life/sdk/auth/AuthContract.kt
sdk-core/src/main/java/care/data4life/sdk/auth/UserService.kt
sdk-core/src/main/java/care/data4life/sdk/network/model/NetworkModelContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/model/VersionList.kt
sdk-core/src/test/java/care/data4life/sdk/auth/UserServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/VersionListTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/VersionTest.kt

This unwires the current Versioning implementation.
The current Versioning need more refinement in order to be future proof.
This is part of [SDK-574](https://gesundheitscloud.atlassian.net/browse/SDK-574).
It depends on #112.
It makes some minor cleanups in the implementation and removes its usage from the UserService and the AndroidClient.
The tests are now aligned and the tests in UserService had been removed, since this

[SDK-574] Change Versioning

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Versions.kt

This updates the FHIR-SDK dependency.
This solves [SDK-576](https://gesundheitscloud.atlassian.net/browse/SDK-576) and is part of [SDK-575](https://gesundheitscloud.atlassian.net/browse/SDK-575)
FHIR-SDK 1.3.1 -> 1.4.0
No additional tests needed

Bump FHIR-SDK 1.3.1 -> 1.4.0

---

CHANGELOG.adoc
README.adoc
buildSrc/src/main/kotlin/LibraryConfig.kt

Prepare Release 1.11.0

---

sdk-core/src/main/java/care/data4life/sdk/network/model/DecryptedRecordGuard.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/CommonKeyResponseTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/DocumentUploadResponseTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/EncryptedKeyTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/EncryptedRecordTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/LimitGuardTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/UserInfoTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/model/VersionTest.kt

This is a cleanup of the current NetworkModelTests.
All tests in the codebase should be aligned.
This is part of [SDK.563](https://gesundheitscloud.atlassian.net/browse/SDK-563) and depends on #120.
It makes just minor changes to the current NetworkModel tests as well as a smaller change to the `DecryptedRecordGuard`.
No additional tests needed.

[SDK-563] Change NetworkModelTests

---

sdk-core/src/main/java/care/data4life/sdk/data/DataContract.kt
sdk-core/src/main/java/care/data4life/sdk/data/DataResource.kt
sdk-core/src/test/java/care/data4life/sdk/data/DataResourceTest.kt

This refactors the DataResource.
The DataResource can be improved, so we should do that. This is part of [SDK-574](https://gesundheitscloud.atlassian.net/browse/SDK-574) and depends on of #121.
It makes an addition to the interface of the DataResource. Also `asByteArray` does not act any longer as a alias for `value` - it returns a clone of the wrapped value.
A test set for the DataResource had been added.

[SDK-574] Change DataResource

---

sdk-core/src/main/java/care/data4life/sdk/network/Environment.kt
sdk-core/src/main/java/care/data4life/sdk/network/NetworkingContract.kt
sdk-core/src/test/java/care/data4life/sdk/network/EnvironmentTest.kt

This adds test for `Environment`, which was untested so far.
In order to improve the testsbase this PR was made.
This is part of  [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563) and depends on #124.
It makes a minor code changes to the Environment in terms to make the code looking nicer.
The main purpose of the PR is to add the tests.

[SDK-563] Add Environment tests

---

sdk-core/src/main/java/care/data4life/sdk/ApiService.java
sdk-core/src/main/java/care/data4life/sdk/RecordService.kt
sdk-core/src/main/java/care/data4life/sdk/network/IHCService.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceTest.kt

This adds dedicated unittest for the ApiService.
Currently the tests for the ApiService are not in good state - they test partly in integration or with deprecated methods.
This is part of [SDK-566](https://gesundheitscloud.atlassian.net/browse/SDK-566) and depends on #125.
This adds unit tests to cover the current behaviour of the ApiService.
This is all about tests.

[SDK-566] Add ApiService unit tests

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/LibraryConfig.kt
sdk-core/src/main/java/care/data4life/sdk/SdkContract.kt

Prepare release of 1.12.0
Note: This depends on #143

Prepare Release 1.12.0

---

.idea/inspectionProfiles/ktlint.xml

Enable Android Studio checks for Kotlin coding conventions
Have more consistency developing in Kotlin
Updated the shared inspection configuration for Android Studio.

Add Kotlin coding conventions inspections

---

sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt
sdk-core/src/main/java/care/data4life/sdk/network/ApiService.kt
sdk-core/src/main/java/care/data4life/sdk/network/HealthCloudApi.kt
sdk-core/src/main/java/care/data4life/sdk/network/NetworkingContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/util/HealthCloudApiFactory.kt
sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceModuleTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/util/HealthCloudApiFactoryTest.kt

This simply renames the IHCService.
The name is not fitting any longer and is not well carrying the intend of its usage.
This depends on #140.
It simply renames it to HealthCloudApi.
No new tests needed.

Change IHCService to  HealthCloudApi

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Versions.kt
sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt

This updates the Fhir-SDK from 1.4.0 to 1.5.0
We are in need of new resources. This is part of [SDK-575](https://gesundheitscloud.atlassian.net/browse/SDK-575) and [SDK-604](https://gesundheitscloud.atlassian.net/browse/SDK-604).
Simply by changing the version number.
No new tests needed.

[SDK-575] Bump FHIR-SDK 1.4.0 -> 1.5.0

---

sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt
sdk-core/src/test/java/care/data4life/sdk/fhir/ResourceCryptoServiceTest.kt

This makes some housekeeping in regards to the ResourceCryptoService tests.
Currently the ResourceCryptoService tests do not cover all aspects of the ResourceCryptoService and also need alignment with the current test patterns.
This is part of [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563)
It aligns the tests with current test patterns.
This is about test.

[SDK-563] Change ResourceCryptoService tests

---

sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt
sdk-core/src/test/java/care/data4life/sdk/auth/AuthClientTest.kt
sdk-core/src/test/java/care/data4life/sdk/data/DataRecordClientTest.kt
sdk-core/src/test/java/care/data4life/sdk/fhir/FhirRecordClientTest.kt

This adds missing unittests for the AuthClient.
Currently the AuthClient is not covered by tests.
This is part of [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563).
-
Add unittests for the AuthClient.

[SDK-563] Add AuthClient tests

---

sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt
sdk-core/src/main/java/care/data4life/sdk/auth/AuthClient.kt
sdk-core/src/main/java/care/data4life/sdk/auth/AuthContract.kt
sdk-core/src/main/java/care/data4life/sdk/auth/UserService.kt
sdk-core/src/main/java/care/data4life/sdk/crypto/CryptoContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/NetworkingContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/model/NetworkModelContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/model/UserInfo.kt
sdk-core/src/test/java/care/data4life/sdk/auth/AuthClientTest.kt
sdk-core/src/test/java/care/data4life/sdk/auth/UserServiceTest.kt

This makes a rewrite of the already existing UserServiceTests
The tests are currently hard to understand and cover not all cases.
This is part of [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563).
However it makes some tiny changes on the UserSerivce in terms of naming.
This aligns the structure with the already established pattern. Also ist adds new test cases for uncovered behaviour.

[SDK-563] Change UserService tests

---

CHANGELOG.adoc
README.adoc
sdk-core/src-gen/main/java/care/data4life/sdk/config/SDKConfig.kt
sdk-doc/src/docs/asciidoc/index.adoc

Prepare Release 1.13.0

---

CHANGELOG.adoc
README.adoc

Prepare Release 1.13.1

---

CHANGELOG.adoc
sdk-core/src/main/java/care/data4life/sdk/network/Environment.kt
sdk-core/src/main/java/care/data4life/sdk/network/NetworkingContract.kt
sdk-core/src/main/java/care/data4life/sdk/network/util/ClientFactory.kt
sdk-core/src/test/java/care/data4life/sdk/network/EnvironmentTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/util/CertificatePinnerFactoryTest.kt
sdk-core/src/test/java/care/data4life/sdk/network/util/ClientFactoryTest.kt

This removes the certificate pinning for S4H.
The modus operandi for S4H changed, so this needs to be done to unbreak the SDK for S4H.
It removes all traces of S4H in `Environment` and adds a switch for the the Pinner. 
A new tests had been added and the unittests for `Environment` had been adjusted.

Remove CertificatePin for S4H

---

sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentContract.kt
sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentService.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceCreationRecordModuleTest.kt
sdk-core/src/test/java/care/data4life/sdk/RecordServiceModuleTestFlowHelper.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/AttachmentGuardianTest.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/AttachmentServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/CompatibilityValidatorTest.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/FileServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/test/fake/CryptoServiceFake.kt

This makes a rewrite of the current tests for the AttachmentService to align them with the established test pattern.
This is part of [SDK-563](https://gesundheitscloud.atlassian.net/browse/SDK-563).
There is one change which rolls back a untracked behaviour change which was introduced in December and does not align with the previous intended version.
This is mostly about tests.

[SDK-563] Change AttachmentService tests

---

sdk-core/src/main/java/care/data4life/sdk/RecordService.kt
sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentContract.kt
sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentDownloadHelper.kt
sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentInternalContract.kt
sdk-core/src/main/java/care/data4life/sdk/attachment/AttachmentService.kt
sdk-core/src/main/java/care/data4life/sdk/wrapper/SDKImageResizer.kt
sdk-core/src/main/java/care/data4life/sdk/wrapper/WrapperContract.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/AttachmentDownloadHelperTest.kt
sdk-core/src/test/java/care/data4life/sdk/attachment/AttachmentServiceTest.kt
sdk-core/src/test/java/care/data4life/sdk/wrapper/SDKResizerTest.kt

This makes a small refactoring of the AttachmentService.
This was made to break the AttachmentService down it to several pieces to increase testability and understanding of its features.
This is part of [SDK-574](https://gesundheitscloud.atlassian.net/browse/SDK-574) and depends on #164.
In introduces 2 new classes AttachmentDownloadHelper and SDKResizer.
The DownloadHelper takes care of all direct interactions with Attachments during the Download.
The SDKResizer is a convenience wrapper which encapsulates the Logging and the Fetch on a edge case while dealing with resizing.
The AttachmentService itself got cleaned up and made use of the new introduced Classes.
New units got new tests exiting tests had been modified to reflect the changes. Also a new tests had been added for the …

[SDK-574] Change AttachmentService

---

.github/CODEOWNERS

Add Alessio

---

CHANGELOG.adoc
README.adoc

Prepare Release 1.14.0

---

CHANGELOG.adoc
buildSrc/src/main/kotlin/Version.kt
sdk-core/src/test/java/care/data4life/sdk/wrapper/FhirElementFactoryTest.kt

This makes used of the patched FHIR-Helper version, which includes the patch FHIR-Java version.
n/a
By bumping to 1.7.1
n/a

Bump FHIR-Helpers

---

gradle/deploy-android-sdk.gradle
gradle/deploy-android.gradle
gradle/deploy-java.gradle

Fix deployment scripts, which are not using the right env variables
Changed from `PACKAGE_REGISTRY_*` to `PACKAGE_REGISTRY_UPLOAD_*`

Fix deployment

---

buildSrc/src/main/kotlin/care/data4life/gradle/core/config/LibraryConfig.kt

Fix groupId to avoid `care.data4life.hc-sdk-kmp.hc-sdk-kmp` instead of `care.data4life.hc-sdk-kmp`

Fix groupId

---

CHANGELOG.adoc
docs/04_sdk_auth.adoc
sample-android/src/main/java/care/data4life/sample/MainActivity.java

The HC-Auth-SDK-KMP was changed and the documentation was missing this information
N/A

Change Auth documentation
